url: "https://api.github.com"
user:
  name_max_length: 50
  email_max_length: 255
  password_min_length: 6
  password_reset_token_expiration: <%= 2.hours.ago %>
  VALID_EMAIL_REGEX: \A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z
  gravatar:
    default_size: 80
    index_size: 50
mailer:
  from: "noreply@example.com"
session:
  remember_me_value: "1"
